### ISSUE TITLE
`set-output` command deprecation warning

### ISSUE THREAD

**Issue by VirenMistrys** [georgealton/iam-sarif-report#237]
Hello,
I am using your action on IAM Validation, and I have found this message below:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
I am raising this just to make you aware of it and check if you plan to update it in the future.

**Comment by georgealton** [comment]
Hi @VirenMistrys thanks for using my action and for letting me know. I've noticed this in a few of the workflows I use this too and been meaning to update it for a while.

I'll take a look at this soon.
